draw_set_font(fnt_game)
draw_set_halign(fa_center)
draw_text(room_width / 2, (room_height / 2), "Congratulations! You beat the game!")
draw_set_font(fnt_subtitle)
draw_text(room_width / 2, (room_height / 2) + 200, "Press space to restart")