draw_set_font(fnt_win)
draw_text(room_width / 2, 400, "Congratulations! You beat the game!")
draw_set_font(fnt_game)
draw_text(room_width / 2, 550, "Final Score: " + string(global.score))
draw_text(room_width / 2, 650, "Press space to restart")